services:
  # Message Queue Service - Apache Artemis
  reproartemis:
    image: apache/activemq-artemis:2.34.0
    ports:
      - "40081:8161"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: password
      ANONYMOUS_LOGIN: "true"
    networks:
      - app-network

  # Ping Service
  ping:
    image: alpenglow411/ping:20250924134358
    build:
      context: ./ping
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
    environment:
      - MQ_HOST=reproartemis
      - MQ_PORT=61616
      - MQ_USER=admin
      - MQ_PASS=password
    networks:
      - app-network
    depends_on:
      - reproartemis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Pong Service
  pong:
    image: alpenglow411/pong:20250924134358
    build:
      context: ./pong
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
    environment:
      - MQ_HOST=reproartemis
      - MQ_PORT=61616
      - MQ_USER=admin
      - MQ_PASS=password
    networks:
      - app-network
    depends_on:
      - reproartemis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Load Balancer / Reverse Proxy
  caddy:
    image: alpenglow411/caddy:20250924134358
    build:
      context: ./caddy
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    ports:
      - "40080:80"
    networks:
      - app-network
    depends_on:
      - ping
      - pong

networks:
  app-network:
    external: true
    name: enclave
